# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.2
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: ludko2@gmail.com
author_name: Ludovit Scholtz
contract_name: gas_station
preset_name: production
project_name: AVMGasStationFrontend

